'use strict';
(()=>{
 const $=id=>document.getElementById(id),A=LAB.Art,app=$('app'),worldCanvas=$('world'),expCanvas=$('experiment');
 const ctx=worldCanvas.getContext('2d',{alpha:false}),gx=expCanvas.getContext('2d',{alpha:false});
 if(!ctx||!gx){document.body.innerHTML='<main class="no-script"><h1>Aditya’s Lab</h1><p>This browser cannot draw the game.</p><a href="notebook.html">Read the complete portfolio →</a></main>';return;}
 const storageKey='adityas-lab-worlds-v1',query=window.matchMedia('(prefers-reduced-motion: reduce)');
 let saved={},storageAvailable=true;try{saved=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch(e){storageAvailable=false;/* Storage may be blocked. Gameplay still works. */}
 if(!saved||typeof saved!=='object')saved={};
 const allIds=new Set(LAB.worlds.flatMap(w=>w.games.map(g=>g.id)));
 const state={world:null,index:0,completed:new Set(Array.isArray(saved.completed)?saved.completed.filter(x=>allIds.has(x)):[]),gentle:typeof saved.gentle==='boolean'?saved.gentle:query.matches,crt:saved.crt!==false,sound:false,x:125,cam:0,face:1,vy:0,jump:0,dogX:91,pet:0};
 let W=0,H=0,background=null,game=null,keys=new Set(),pointers=new Map(),moveTo=null,ground=0,clock=0,last=performance.now(),lastRender=0,raf=0,travelTimer=0,toastTimer=0,hearts=[],targetNodes=new Map(),dragging=false,soundContext=null,gameActions=[],portals=[],portalSize=1;
 const total=LAB.total,portalXs=[300,615,930,1245,1560],worldLength=1840;
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify({completed:[...state.completed],gentle:state.gentle,crt:state.crt}));storageAvailable=true;}catch(e){storageAvailable=false;}}
 function updateProgress(){const text=`${state.completed.size} / ${total}`;$('progress').textContent=text;$('atlasProgress').textContent=`${text} discoveries · ${storageAvailable?'saved on this device':'this tab only; storage unavailable'}`;if(state.world)$('worldCount').textContent=`${state.world.games.filter(g=>state.completed.has(g.id)).length} / ${state.world.games.length} found`;document.querySelectorAll('.concept').forEach((b,i)=>b.classList.toggle('done',state.world&&state.completed.has(state.world.games[i]?.id)));document.querySelectorAll('.atlas-card').forEach((b,i)=>{let w=LAB.worlds[i];b.querySelector('.card-count').textContent=w.games.filter(g=>state.completed.has(g.id)).length+' / '+w.games.length;});}
 function toast(msg){clearTimeout(toastTimer);$('toast').textContent=msg;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3400);}
 function tone(kind='step'){if(!state.sound)return;try{if(!soundContext)soundContext=new(window.AudioContext||window.webkitAudioContext)();soundContext.resume();const notes=kind==='win'?[523.25,659.25,783.99]:kind==='pet'?[587.33,880]:[220,329.63];notes.forEach((n,i)=>{let osc=soundContext.createOscillator(),gain=soundContext.createGain(),t=soundContext.currentTime+i*.085;osc.type='triangle';osc.frequency.value=n;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.045,t+.01);gain.gain.exponentialRampToValueAtTime(.001,t+.23);osc.connect(gain);gain.connect(soundContext.destination);osc.start(t);osc.stop(t+.25);});}catch(e){state.sound=false;$('soundButton').setAttribute('aria-pressed','false');}}
 function resetMovement(){keys.clear();pointers.clear();moveTo=null;dragging=false;document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));if(game)game.onPointer('cancel',{x:0,y:0,down:false});}
 function saveHash(hash){try{history.replaceState(null,'',hash);}catch(e){/* file previews need no history permissions */}}
 function resize(){W=app.clientWidth;H=app.clientHeight;const scale=2;worldCanvas.width=Math.ceil(W/scale);worldCanvas.height=Math.ceil(H/scale);ctx.imageSmoothingEnabled=false;ground=H*.79;portalSize=H<640?.70:H<740?.88:1;let biome=state.world?state.world.games[state.index].biome:'hub';background=A.makeBackground(biome,worldCanvas.width,worldCanvas.height,42+state.index*33);if(game){const stage=$('gameStage');stage.style.height='';stage.style.aspectRatio='';let sr=stage.getBoundingClientRect(),shell=$('experimentShell').getBoundingClientRect(),nav=document.querySelector('.concept-nav').getBoundingClientRect(),foot=document.querySelector('.bottom-bar').getBoundingClientRect();let sideBySide=nav.right<shell.left;let bottom=sideBySide?foot.top-12:Math.min(nav.top-14,foot.top-12);let available=bottom-shell.top-(shell.height-sr.height);stage.style.height=Math.max(105,Math.min(sr.height,available))+'px';stage.style.aspectRatio='auto';const r=stage.getBoundingClientRect();game.W=r.width<550?460:700;game.H=Math.round(game.W*(r.height/r.width));expCanvas.width=game.W;expCanvas.height=game.H;gx.imageSmoothingEnabled=false;}drawWorld();}
 function renderActions(actions){gameActions=actions;const host=$('gameActions');const focused=host.contains(document.activeElement)?document.activeElement.dataset.action:null;host.classList.toggle('has-range',actions.some(a=>a.type==='range'));host.classList.toggle('two-sliders',actions.filter(a=>a.type==='range').length>1);host.replaceChildren();for(const [i,a]of actions.entries()){if(a.type==='range'){let label=document.createElement('label'),span=document.createElement('span');span.textContent=a.label;let range=document.createElement('input');range.type='range';range.min=a.min;range.max=a.max;range.step=a.step||1;range.value=a.value;range.setAttribute('aria-label',a.label);range.addEventListener('input',()=>a.fn(Number(range.value)));label.append(span,range);host.append(label);}else{let b=document.createElement('button');b.type='button';b.textContent=a.label;if(a.ariaLabel)b.setAttribute('aria-label',a.ariaLabel);if(typeof a.pressed==='boolean')b.setAttribute('aria-pressed',String(a.pressed));b.classList.toggle('key',!!a.key);b.dataset.action=String(i);b.addEventListener('click',()=>{a.fn();});host.append(b);}}if(focused!==null)host.querySelector('[data-action="'+focused+'"]')?.focus({preventScroll:true});if(game)requestAnimationFrame(resize);}
 function complete(id){if(!state.completed.has(id)){state.completed.add(id);persist();updateProgress();tone('win');let finished=state.completed.size===total;toast(finished?'Every world explored. You found the whole lab. ✦':'✦ Discovery added to your passport');}else tone('win');}
 function buildGame(){const def=state.world.games[state.index];targetNodes.clear();$('targets').replaceChildren();$('feedback').textContent='Try it. There is no wrong turn.';$('feedback').classList.remove('success');$('experimentName').textContent=def.name;$('experimentIndex').textContent=`EXPERIMENT ${String(state.index+1).padStart(2,'0')} / ${String(state.world.games.length).padStart(2,'0')}`;$('objective').textContent=def.verb;expCanvas.setAttribute('aria-label',def.name+'. '+def.verb);game=LAB.Games.create(def,{feedback(msg,ok){$('feedback').textContent=msg;$('feedback').classList.toggle('success',!!ok);},actions:renderActions,complete});
  const host=$('concepts');host.replaceChildren();state.world.games.forEach((d,i)=>{let b=document.createElement('button');b.className='concept'+(i===state.index?' active':'')+(state.completed.has(d.id)?' done':'');b.type='button';b.title=d.name;b.setAttribute('aria-label',d.name);if(i===state.index)b.setAttribute('aria-current','step');b.textContent=String(i+1).padStart(2,'0');let span=document.createElement('span');span.textContent=d.name;b.append(span);b.addEventListener('click',()=>enter(state.world.id,d.id));host.append(b);});updateProgress();resize();requestAnimationFrame(()=>host.querySelector('.active')?.scrollIntoView({block:'nearest',inline:'center',behavior:'instant'}));}
 function enter(id,gameId){clearTimeout(toastTimer);$('toast').hidden=true;let w=LAB.worlds.find(w=>w.id===id);if(!w)return;resetMovement();const idx=typeof gameId==='string'?w.games.findIndex(g=>g.id===gameId):typeof gameId==='number'?gameId:0;clearTimeout(travelTimer);app.classList.add('traveling');travelTimer=setTimeout(()=>{state.world=w;state.index=idx>=0&&idx<w.games.length?idx:0;app.classList.add('is-world');$('hubUI').hidden=true;$('worldUI').hidden=false;$('location').textContent=w.name.toUpperCase();$('worldOrg').textContent=w.games[state.index].org||w.org;$('worldTitle').textContent=w.name;document.documentElement.style.setProperty('--accent',w.color);buildGame();saveHash('#/'+w.id+'/'+w.games[state.index].id);closeDialogs();app.classList.remove('traveling');tone();},state.gentle?0:130);}
 function home(){clearTimeout(toastTimer);$('toast').hidden=true;resetMovement();clearTimeout(travelTimer);state.world=null;state.index=0;game=null;targetNodes.clear();app.classList.remove('is-world','traveling');$('hubUI').hidden=false;$('worldUI').hidden=true;$('location').textContent='WORLDS WITHIN WORLDS';document.documentElement.style.setProperty('--accent','#f4bf72');saveHash('#/');closeDialogs();resize();}
 function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
 function openDialog(id){resetMovement();if($(id).open)return;$(id).showModal();}
 function openMap(){if($('atlas').open){$('atlas').close();return;}updateProgress();openDialog('atlas');}
 function jump(){if(!state.world&&state.jump===0){state.vy=310;tone('step');}}
 function nearest(){return portalXs.reduce((best,x,i)=>Math.abs(x-state.x)<Math.abs(portalXs[best]-state.x)?i:best,0);}
 function interact(){if(state.world)return;let n=nearest();if(Math.abs(portalXs[n]-state.x)<210)enter(LAB.worlds[n].id);else{moveTo=portalXs[n];toast('Walking to the next portal.');}}
 function pet(){state.pet++;hearts.push({x:state.dogX,y:ground-35,t:0});tone('pet');toast(state.pet===1?'Good dog. Better research companion.':state.pet===3?'Achievement: peer review by dog. ♥':state.pet%5===0?'The dog recommends more world models.':'A very good research assistant.');}
 function syncTargets(){if(!game)return;const host=$('targets'),keep=new Set(),r=$('gameStage').getBoundingClientRect(),sx=game.W/r.width,sy=game.H/r.height;for(const t of game.targets){keep.add(t.id);let node=targetNodes.get(t.id);if(!node){node=document.createElement('button');node.className='game-target';node.type='button';node.dataset.target=t.id;node.addEventListener('click',()=>node._action?.());host.append(node);targetNodes.set(t.id,node);}node._action=t.fn;node.setAttribute('aria-label',t.label);node.title=t.label;let tw=Math.max(t.w,44*sx),th=Math.max(t.h,44*sy),tx=Math.max(0,Math.min(game.W-tw,t.x-(tw-t.w)/2)),ty=Math.max(0,Math.min(game.H-th,t.y-(th-t.h)/2));node.style.cssText=`left:${tx/game.W*100}%;top:${ty/game.H*100}%;width:${tw/game.W*100}%;height:${th/game.H*100}%;`;}for(const[id,node]of targetNodes){if(!keep.has(id)){node.remove();targetNodes.delete(id);}}}
 function drawWorld(){if(!background)return;const c=ctx,w=worldCanvas.width,h=worldCanvas.height,biome=state.world?state.world.games[state.index].biome:'hub';c.drawImage(background,0,0);A.ambience(c,biome,w,h,clock,state.gentle);if(!state.world){
   const gy=ground/2,cam=state.cam/2;
   // The foreground is a real scrollable place, not a static picture behind cards.
   for(let i=0;i<portalXs.length;i++){let px=portalXs[i]/2-cam;const wd=LAB.worlds[i];if(px>-90&&px<w+90){c.save();c.translate(px,gy);c.scale(portalSize,portalSize);A.booth(c,0,0,wd.id,wd.color,clock,wd.games.every(g=>state.completed.has(g.id)));c.restore();A.lantern(c,px-128*portalSize,gy-54,wd.color);}}
   let px=(state.x-state.cam)/2,yy=gy-state.jump/2;A.glow(c,px,gy,15,'#ffdca3',.06);A.explorer(c,px,yy,clock,state.face,keys.size>0||pointers.size>0||moveTo!==null);A.dog(c,(state.dogX-state.cam)/2,gy,clock,state.face,Math.abs(state.dogX-(state.x-35*state.face))>8);
   for(const heart of hearts)A.heart(c,(heart.x-state.cam)/2,heart.y/2-heart.t*16,1.1);
   for(let i=0;i<portals.length;i++){let bx=portalXs[i]-state.cam,by=ground-206*portalSize-60;const visible=bx>-130&&bx<W+130;portals[i].hidden=!visible;portals[i].style.left=(bx-(W<601?66.5:W<901?73.5:80))+'px';portals[i].style.top=by+'px';}
   $('petButton').style.left=(state.dogX-state.cam-20)+'px';$('petButton').style.top=(ground-44)+'px';
  }else{
   let col=state.world.color;const gy=h*.79;A.explorer(c,Math.max(17,w*.09),gy,clock,1,false);A.dog(c,Math.max(7,w*.09)-15,gy,clock,1,false);if(w>350){A.lantern(c,w*.91,gy-54,col);A.robot(c,w*.92,gy,1.15,col,clock);}
  }
 }
 function animate(now){raf=requestAnimationFrame(animate);if(document.hidden){last=now;return;}let elapsed=(now-last)/1000;last=now;const dt=Math.min(elapsed,.034);const modal=!!document.querySelector('dialog[open]');if(!modal&&!state.gentle)clock+=dt;
  if(!modal&&!state.world){let m=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);for(const v of pointers.values())m+=v;if(moveTo!==null){let d=moveTo-state.x;if(Math.abs(d)<5)moveTo=null;else m=Math.sign(d);}m=Math.max(-1,Math.min(1,m));if(m){state.face=m;state.x=Math.max(60,Math.min(worldLength-70,state.x+m*220*dt));}const targetCam=Math.max(0,Math.min(Math.max(0,worldLength-W),state.x-W*.38));state.cam=state.gentle?targetCam:state.cam+(targetCam-state.cam)*Math.min(1,dt*5);state.dogX+=(state.x-35*state.face-state.dogX)*Math.min(1,dt*5);if(state.jump>0||state.vy>0){state.jump+=state.vy*dt;state.vy-=730*dt;if(state.jump<0){state.jump=0;state.vy=0;}}}
  hearts=hearts.map(h=>({...h,t:h.t+dt})).filter(h=>h.t<2);
  if(game&&!modal){game.t+=dt;game.tick(dt);}
  if(now-lastRender>1000/30){lastRender=now;drawWorld();if(game){game.targets=[];game.draw(gx,state.gentle?0:clock);syncTargets();}}
 }
 // All navigation remains available even without walking through the city.
 LAB.worlds.forEach((w,i)=>{let b=document.createElement('button');b.className='portal-label';b.style.setProperty('--portal',w.color);b.setAttribute('aria-label','Enter '+w.name);b.innerHTML=`<small>${w.n} / ${w.org.split(' · ')[0].toUpperCase()}</small><strong>${w.name} ↗</strong>`;b.addEventListener('click',()=>enter(w.id));$('hubPortals').append(b);portals.push(b);
   let card=document.createElement('button');card.className='atlas-card';card.setAttribute('aria-label','Travel to '+w.name);let cv=document.createElement('canvas');cv.setAttribute('aria-hidden','true');A.thumbnail(cv,w);let cp=document.createElement('span');cp.className='card-copy';let title=document.createElement('strong');title.style.color=w.color;title.textContent=w.name;let sm=document.createElement('small');sm.textContent=w.desc;cp.append(title,sm);let count=document.createElement('span');count.className='card-count';card.append(cv,cp,count);card.addEventListener('click',()=>enter(w.id));$('atlasCards').append(card);
 });
 $('home').onclick=home;$('backCity').onclick=home;$('cityFromMap').onclick=home;$('mapButton').onclick=openMap;$('exploreButton').onclick=openMap;$('passportButton').onclick=openMap;$('settingsButton').onclick=()=>openDialog('settings');$('petButton').onclick=pet;$('hopButton').onclick=jump;$('enterButton').onclick=interact;
 $('prevGame').onclick=()=>{if(state.world)enter(state.world.id,(state.index-1+state.world.games.length)%state.world.games.length);};$('nextGame').onclick=()=>{if(state.world)enter(state.world.id,(state.index+1)%state.world.games.length);};
 $('resetGame').onclick=()=>{if(state.world){resetMovement();buildGame();}};
 $('aboutExperiment').onclick=()=>{if(!game)return;$('noteOrg').textContent=game.def.org||state.world.org;$('noteTitle').textContent=game.def.name;$('noteText').textContent=game.def.note;openDialog('note');};
 $('soundButton').onclick=()=>{state.sound=!state.sound;$('soundButton').setAttribute('aria-pressed',String(state.sound));$('soundButton').setAttribute('aria-label',state.sound?'Mute sound':'Enable sound');$('soundButton').title=state.sound?'Sound on':'Sound off';if(state.sound)tone();};
 $('reduceMotion').checked=state.gentle;$('reduceMotion').onchange=e=>{state.gentle=e.target.checked;persist();};$('crt').checked=state.crt;document.querySelector('.scanlines').hidden=!state.crt;$('crt').onchange=e=>{state.crt=e.target.checked;document.querySelector('.scanlines').hidden=!state.crt;persist();};
 $('resetProgress').onclick=()=>{if(confirm('Clear your local discoveries? This does not change the portfolio.')){state.completed.clear();persist();updateProgress();if(state.world)buildGame();toast('A fresh passport. All worlds are still open.');}};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});d.addEventListener('close',resetMovement);});
 // Keep keyboard navigation within the currently open dialog, including wraparound.
 document.querySelectorAll('dialog').forEach(d=>d.addEventListener('keydown',e=>{
  if(e.key!=='Tab')return;
  const focusable=[...d.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex="0"]')].filter(el=>el.getClientRects().length);
  if(!focusable.length){e.preventDefault();return;}
  const first=focusable[0],last=focusable[focusable.length-1];
  if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}
  else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}
 }));
 document.addEventListener('keydown',e=>{if(e.ctrlKey||e.altKey||e.metaKey||e.target.closest('input,textarea,select')||document.querySelector('dialog[open]'))return;if(e.target.closest('button,a')&&(e.key===' '||e.key==='Enter'))return;let k=e.key.toLowerCase();if(['a','d','arrowleft','arrowright',' ','e','m','escape'].includes(k))e.preventDefault();if(k==='m'&&!e.repeat)openMap();else if(k==='escape'&&!e.repeat)home();else if(k==='e'&&!e.repeat)interact();else if(k===' '&&!e.repeat)jump();else keys.add(k);});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
 document.querySelectorAll('[data-move]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();moveTo=null;try{b.setPointerCapture(e.pointerId);}catch(e){/* A canceled pointer may already be gone. */}pointers.set(e.pointerId,Number(b.dataset.move));b.classList.add('pressed');});const up=e=>{pointers.delete(e.pointerId);b.classList.remove('pressed');};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);});
 worldCanvas.addEventListener('pointerdown',e=>{if(!state.world){moveTo=Math.max(60,Math.min(worldLength-60,e.clientX+state.cam));if(Math.abs(e.clientX-(state.dogX-state.cam))<30&&Math.abs(e.clientY-ground)<48){moveTo=null;pet();}}});
 function pointer(e,type){if(!game)return;const r=expCanvas.getBoundingClientRect();if(type==='down'){dragging=true;try{expCanvas.setPointerCapture(e.pointerId);}catch(e){/* Pointer cancellation is safe. */}}if(type==='up'||type==='cancel')dragging=false;game.onPointer(type,{x:(e.clientX-r.left)/r.width*game.W,y:(e.clientY-r.top)/r.height*game.H,down:dragging});e.preventDefault();}expCanvas.addEventListener('pointerdown',e=>pointer(e,'down'));expCanvas.addEventListener('pointermove',e=>pointer(e,'move'));expCanvas.addEventListener('pointerup',e=>pointer(e,'up'));expCanvas.addEventListener('pointercancel',e=>pointer(e,'cancel'));expCanvas.addEventListener('lostpointercapture',()=>{if(dragging){dragging=false;game?.onPointer('cancel',{x:0,y:0,down:false});}});
 window.addEventListener('blur',resetMovement);document.addEventListener('visibilitychange',()=>{resetMovement();last=performance.now();if(document.hidden&&soundContext)soundContext.suspend();});window.addEventListener('resize',resize);if(window.visualViewport)visualViewport.addEventListener('resize',resize);
 function route(){const [w,g]=location.hash.replace(/^#\/?/,'').split('/');if(LAB.worlds.some(v=>v.id===w))enter(w,g);else if(location.hash&&location.hash!=='#/')home();}window.addEventListener('hashchange',route);
 updateProgress();resize();route();raf=requestAnimationFrame(animate);
 // Non-mutating diagnostics + explicit navigation used by the included smoke tests.
 window.LAB_APP={enter,home,getState:()=>({world:state.world?.id||'hub',experiment:game?.def.id||null,index:state.index,completed:[...state.completed],total,playerX:state.x,cameraX:state.cam,gentle:state.gentle,sound:state.sound,moving:keys.size+pointers.size,gameSize:game?{w:game.W,h:game.H}:null,experimentState:game?.snapshot?.()||null}),getTargets:()=>game?.targets.map(({id,label,x,y,w,h})=>({id,label,x,y,w,h}))||[]};
})();
