/* Editorial source: Aditya's descriptions in this conversation, not inferred results. */
'use strict';
window.LAB = window.LAB || {};
LAB.worlds = [
 {id:'signal',n:'01',name:'Signal Coast',org:'Nokia · data science',tag:'Find the signal.',color:'#76e0f2',biome:'coast',desc:'Time-series forecasting · anomaly detection',
  games:[
   {id:'anomaly',name:'The outliers',verb:'Catch the three broken signals.',kind:'anomaly',biome:'coast',note:'Anomaly detection in time series. This scene uses synthetic readings with three injected spikes; it is not a trained detector.'},
   {id:'forecast',name:'Tomorrow, maybe',verb:'Complete the pattern beyond the horizon.',kind:'forecast',biome:'aurora',note:'Time-series forecasting. Match a continuation to the observed pattern. The uncertainty ribbon is illustrative, not a calibrated forecast.'}
  ]},
 {id:'agents',n:'02',name:'Agent Afterhours',org:'Nokia Bell Labs · multi-agent systems',tag:'Trace the trouble.',color:'#c19cff',biome:'city',desc:'Computer use · causality · context · interpretability',
  games:[
   {id:'cascade',name:'Patient zero',verb:'Stop the cascade at its source.',kind:'cascade',biome:'city',note:'Cascading failure detection and causality in multi-agent systems. A known synthetic dependency graph lets you intervene on upstream context or downstream symptoms. It illustrates intervention, not causal discovery.'},
   {id:'computer',name:'The night shift',verb:'Inspect. Refresh context. Deploy. Verify.',kind:'computer',biome:'terminal',note:'Computer-use agents, task-specific agents and context management. Operate a simulated desktop with a planner, a context manager, a network operator and a verifier. No real computers or networks are controlled.'},
   {id:'context',name:'Memory lane',verb:'Keep the useful context. Drop the stale copy.',kind:'context',biome:'memory',note:'Context management in agents: relevance, freshness and bounded memory across handoffs. Select the two useful records for a synthetic task; the context budget is part of the puzzle.'},
   {id:'tasks',name:'The right pair of hands',verb:'Give each task to its specialist.',kind:'tasks',biome:'automata',note:'Task-specific agents, orchestration and role specialization. Match observation, network routing and verification jobs to the appropriate agents. The specialties are authored for the puzzle.'},
   {id:'network',name:'Packet courier',verb:'Connect the packet. Avoid the dead router.',kind:'network',biome:'rain',note:'Agents in networking, network-aware planning and resource brokering. Route a packet through a small synthetic topology. This is a connectivity puzzle, not a network-performance benchmark.'},
   {id:'reward',name:'Goodhart arcade',verb:'Reward the task, not the busywork.',kind:'reward',biome:'arcade',note:'Reward hacking, agent alignment, intent, personalization with small language models, and steering feature vectors in action spaces. The two routes make a proxy/objective mismatch visible; the agents follow scripted incentives.'},
   {id:'intent',name:'The Glasshouse',verb:'Change the intent. Trace the choice.',kind:'intent',biome:'glasshouse',org:'Interpretable ML · multi-agent research',note:'I worked on interpretable ML, studying how human intent shapes the reasoning of intelligent agents in cooperative and competitive settings. Circuit tracing was one of the approaches I explored. In this game, human intent and agent incentives are separate controls. Two energy cells can be split equally, relayed to the faster courier B, or kept by A. The numbers are authored utilities, not probabilities. The circuit is hand-wired: its features, weights and action scores are authored, not extracted from a trained model. Muting the intent features is a controlled intervention in that toy circuit, not real-model circuit tracing. The intact and muted panels hold the scene, incentives and weights fixed. A changed score need not change the selected action. These outcomes do not characterize all cooperative or competitive agents.'}
  ]},
 {id:'depin',n:'03',name:'The Open Grid',org:'Nokia Bell Labs · decentralized infrastructure',tag:'Trade. Allocate. Trust.',color:'#f4c16c',biome:'desert',desc:'Energy trading · compute · self-sovereign identity',
  games:[
   {id:'compute',name:'GPU dock',verb:'Fit each job into the smallest usable GPU.',kind:'compute',biome:'orbital',note:'Decentralized compute, double-auction market design and heterogeneous ML resource allocation. The game is a simplified capacity-and-price matching puzzle, not a complete auction implementation. Related systems work includes Docker, Kubernetes, tokenization, Solana and Substrate.'},
   {id:'energy',name:'Sun exchange',verb:'Move eight units of surplus sunlight.',kind:'energy',biome:'desert',note:'Decentralized energy trading, including federated learning and renewable-energy verification. Connect a surplus producer to buyers whose bids meet the ask. Units and prices are fictional; the puzzle conserves energy but does not solve power flow.'},
   {id:'identity',name:'The trust gate',verb:'A signature alone is not admission.',kind:'identity',biome:'vault',note:'Self-sovereign identity for DePINs: provider identity, attestation and provisioning. This toy gate requires a trusted issuer, an unexpired credential and no revocation. It does not perform cryptographic verification.'}
  ]},
 {id:'mbodi',n:'04',name:'Geometry Gardens',org:'Mbodi AI · perception, reasoning & planning',tag:'See what you can do.',color:'#75e3b2',biome:'garden',desc:'Reconstruction · geometry · scene graphs · affordances',
  games:[
   {id:'reconstruct',name:'Hidden in plain sight',verb:'Visit three views. Reveal the whole object.',kind:'reconstruct',biome:'ruins',note:'Scene reconstruction and 3D geometry. Combine complementary viewpoints to reveal a synthetic object. The illustration is not a reconstruction algorithm.'},
   {id:'graph',name:'First things first',verb:'Move the crate. Open the drawer. Get the part.',kind:'graph',biome:'garden',note:'Scene graph theory, reasoning and planning. Object relations determine which actions are available; the state and graph update as you act.'},
   {id:'affordance',name:'A handle on things',verb:'Find the part the gripper can use.',kind:'affordance',biome:'underwater',note:'Affordance learning connects object parts with possible interactions. Select the mug handle, then the drawer handle. These affordances are authored for the toy scene, not learned predictions.'}
  ]},
 {id:'nirvana',n:'05',name:'Worlds Within',org:'Nirvana Robotics · robot learning',tag:'Imagine it. Then act.',color:'#f5a2c8',biome:'moon',desc:'Ego retargeting · representation learning · contact · RL',
  games:[
   {id:'ego',name:'Different arms. Same goal.',verb:'Guide the robot to the demonstrated contact.',kind:'ego',biome:'moon',note:'Ego retargeting: preserving task and contact information across viewpoint and embodiment changes. Two-link inverse kinematics drives the robot arm here; this is not a human-to-robot retargeting model.'},
   {id:'augment',name:'Same thing. New world.',verb:'Find the same shape across different worlds.',kind:'augment',biome:'dream',note:'Data augmentation for representation learning. Match positive views of the same object despite changes in appearance, viewpoint and background. The embedding plot is an illustration of the desired invariance, not learned embeddings.'},
   {id:'cloth',name:'Soft worlds',verb:'Carry the glowing cloth corner to the target.',kind:'cloth',biome:'glacier',note:'Real2Sim2Real for deformable objects. A small Verlet cloth solver makes manipulation tangible. The real / twin / cousin labels are synthetic scene modes, not evidence of physical transfer.'},
   {id:'hinge',name:'Worlds with joints',verb:'Open the articulated lid to the ghost pose.',kind:'hinge',biome:'workshop',note:'Real2Sim2Real for articulated objects. Move a constrained hinge and change its environment. The angular constraint is simulated; no real hardware or reconstruction is involved.'},
   {id:'contact',name:'A delicate balance',verb:'Enough grip to lift. Not enough to crush.',kind:'contact',biome:'furnace',note:'Contact dynamics for manipulated objects. The toy uses gravity, friction and a crush threshold. It omits most contact mechanics and is not a validated physics model.'},
   {id:'steering',name:'A better next rollout',verb:'Steer the path. Reward it. Learn. Test.',kind:'steering',biome:'nebula',note:'Post-training with RL and steering in dense trajectories. This mini-game uses a tiny bandit-style value update over path offsets with collision-based rewards. It is not deep RL or VLA/WAM post-training. Steering, feedback, update and fresh evaluation are separate steps.'},
   {id:'worldmodel',name:'The dream engine',verb:'Predict a future. Try it. Close the gap.',kind:'worldmodel',biome:'cosmos',note:'An interactive nod to world models, foundation-model architectures and planning. A small analytic projectile model makes predictions under an assumed wind; observations reveal model mismatch. This is not a learned world model.'}
  ]}
];
LAB.profile = {
 name:'Aditya Gudal', email:'adityagudal29@gmail.com',
 researchFocus:'I also worked on interpretable ML: how human intent shapes agent reasoning in cooperative and competitive settings, with circuit tracing as one of the approaches.',
 links:[['Email','mailto:adityagudal29@gmail.com'],['GitHub','https://github.com/aditya9729'],['Scholar','https://scholar.google.com/citations?user=bu34FNAAAAAJ'],['LinkedIn','https://linkedin.com/in/aditya-gudal'],['Hugging Face','https://huggingface.co/aditya9729']],
 roles:[
 ['May 2026 — present','Nirvana Robotics','Member of Technical Staff','Ego retargeting; data augmentation for representation learning; Real2Sim2Real for deformable and articulated objects; contact dynamics; RL post-training with steering in dense trajectories. Ego / UMI pipelines, twins and cousins, real2real, foundation-model architectures, VLAs and WAMs, inference optimization, hierarchical planning and failure detection.'],
 ['Sep 2025 — Jun 2026','Mbodi AI','Senior Research Engineer','Scene reconstruction, 3D geometry, scene graph theory, affordance learning, reasoning and planning for manipulation.'],
 ['Apr 2023 — Sep 2025','Nokia Bell Labs','Research Engineer','Computer-use and task-specific agents, cascading failure detection, causality, agents in networking, context management, reward hacking and alignment. Small language models for personalization and intent. Decentralized energy trading and compute, double auctions, self-sovereign identity for DePINs, Solana and Substrate, Docker, Kubernetes and heterogeneous resource allocation.'],
 ['Feb 2021 — Feb 2023','Nokia','Data Scientist','Anomaly detection, time-series forecasting, production ML and MLOps.'],
 ['2018 — 2019','KRIBS-BioNest','Consultant','Genomics data science at the RGCB / Kerala Startup Mission incubator.']
 ],
 papers:[['AI Agent-Driven Network-Aware Decentralized Compute Resource Brokering','OFC 2026 · M3Z.15','https://doi.org/10.1364/OFC.2026.M3Z.15'],['CSR-RAG: An Efficient Retrieval System for Text-to-SQL at Enterprise Scale','Preprint · 2026','https://arxiv.org/abs/2601.06564'],['A Ranking Framework for Network Resource Allocation and Scheduling via Hypergraphs','Preprint · 2025','https://arxiv.org/abs/2506.01571']],
 patents:[['US 2026/0093548 A1','Resource-provider identity, DePIN attestation and provisioning.','https://patents.google.com/patent/US20260093548A1'],['US 2026/0093221 A1','Renewable household energy management with federated ML.','https://patents.google.com/patent/US20260093221A1'],['US 2026/0057398 A1','Renewable-energy verification for EV charging and the grid.','https://patents.google.com/patent/US20260057398A1']],
 education:['Northwestern University · M.S. Machine Learning & Data Science · 2019–2020','University of Mumbai / VESIT · B.E. Electronics Engineering · 2015–2019']
};
LAB.total = LAB.worlds.reduce((n,w)=>n+w.games.length,0);
